# Generated by Django 2.2 on 2020-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='你的名字')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='你的邮箱')),
                ('message', models.TextField(verbose_name='留言')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
            },
        ),
    ]
