# Generated by Django 2.2 on 2020-09-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='你的名字'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
